name: Lint src files with Ruff
on:
    push:
      branches: main
      paths: 
        - 'src/**'
        - 'pyproject.toml'
        - '.github/workflows/ruff.yml'
    pull_request:
      paths: 
        - 'src/**'
        - 'pyproject.toml'
        - '.github/workflows/ruff.yml'
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1